# Generated by Django 5.1.2 on 2024-11-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_remove_child_address_remove_child_guardian_contact_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='hire_date',
            new_name='employment_date',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='contact',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='position',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_hours',
            field=models.CharField(default='9 AM - 5 PM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('children', models.ManyToManyField(related_name='classrooms', to='children.child')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('activity_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
            ],
        ),
    ]
