# Generated by Django 5.1.2 on 2024-11-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_hire_date_staff_employment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='child',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
