# Generated by Django 5.1.2 on 2024-10-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='guardian_phone',
            new_name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian_email',
        ),
    ]
