# Generated by Django 5.1.2 on 2024-11-15 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_date_of_birth'),
        ('parents', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='address',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='child',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='medical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_guardian',
            field=models.ManyToManyField(related_name='children', to='parents.parentguardian'),
        ),
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='child_photos/'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('staff_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
    ]
