# Generated by Django 5.1.2 on 2024-11-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_child_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='child',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='staff_involved',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='IncidentReport',
        ),
    ]
